import type { BrandMeta, BrandKey, CategoryMeta, CategoryKey } from './types';

export const BRANDS: Record<BrandKey, BrandMeta> = {
  mapei: {
    key: 'mapei',
    name: 'MAPEI',
    label: 'MAPEI',
    description: 'Italian leader in adhesives, sealants, and chemical products for building. Over 80 years.',
    origin: 'Italy',
    gcc_url: 'https://www.mapei.com/ae/en',
    color: '#C8102E',
  },
  weber: {
    key: 'weber',
    name: 'Weber',
    label: 'WEBER',
    description: 'Saint-Gobain brand. Full-range building chemicals with strong regional presence (Sodamco Weber).',
    origin: 'France',
    gcc_url: 'https://middleeast.weber',
    color: '#004B87',
  },
  laticrete: {
    key: 'laticrete',
    name: 'LATICRETE',
    label: 'LATICRETE',
    description: 'Global manufacturer of tile and stone installation systems. MEA distribution via Dubai.',
    origin: 'USA',
    gcc_url: 'https://me.laticrete.com',
    color: '#0056A5',
  },
  kerakoll: {
    key: 'kerakoll',
    name: 'Kerakoll',
    label: 'KERAKOLL',
    description: 'Italian green-building chemicals. GreenBuilding Rating system pioneer.',
    origin: 'Italy',
    gcc_url: 'https://gcc.kerakoll.com',
    color: '#00873D',
  },
  pidilite: {
    key: 'pidilite',
    name: 'Pidilite / Puma',
    label: 'PIDILITE / PUMA',
    description: 'Pidilite MEA Chemicals LLC — Dr. Fixit, Fevicol, STAUF, Grupo Puma (Pegoland, Morcemcolor).',
    origin: 'India / Spain',
    gcc_url: 'https://www.pidilitemea.com',
    color: '#E30613',
  },
  xchem: {
    key: 'xchem',
    name: 'XCHEM',
    label: 'X-CHEM',
    description: 'UAE-made construction chemicals. RAK-based manufacturer, H.B. Fuller brand.',
    origin: 'UAE',
    gcc_url: 'https://xchem.ae',
    color: '#002856',
  },
  xcalibur: {
    key: 'xcalibur',
    name: 'X-Calibur',
    label: 'X-CALIBUR',
    description: 'Construction chemistry specialist — structural repair, coatings, and joint sealants.',
    origin: 'USA',
    gcc_url: 'https://www.x-calibur.us',
    color: '#1F2937',
  },
  vetonit: {
    key: 'vetonit',
    name: 'Vetonit / Saveto',
    label: 'VETONIT / SAVETO',
    description: 'Saudi Vetonit Co. — full-range MENA construction chemicals. Since 1981 (Al Rashed Group).',
    origin: 'Saudi Arabia',
    gcc_url: 'https://ae.saveto.com',
    color: '#006A4E',
  },
  colmef: {
    key: 'colmef',
    name: 'Colmef',
    label: 'COLMEF',
    description: 'Italian specialist in high-performance construction chemicals.',
    origin: 'Italy',
    gcc_url: 'https://www.colmef.com',
    color: '#D9261C',
  },
};

export const CATEGORIES: Record<CategoryKey, CategoryMeta> = {
  'tile-adhesives': {
    key: 'tile-adhesives',
    name: 'Tile Adhesives',
    shortName: 'Adhesives',
    description: 'Cementitious (C1/C2), dispersion (D) and reactive (R) adhesives for ceramic, porcelain, stone and mosaic.',
    icon: 'M4 4h16v4H4zM4 12h16v4H4zM4 20h16',
    standards: ['EN 12004', 'ISO 13007'],
  },
  'tile-grouts': {
    key: 'tile-grouts',
    name: 'Tile Grouts',
    shortName: 'Grouts',
    description: 'Cementitious (CG1/CG2) and reactive (RG) grouts for sealing tile joints.',
    icon: 'M3 6h18M3 12h18M3 18h18',
    standards: ['EN 13888', 'ISO 13007'],
  },
  'concrete-repair': {
    key: 'concrete-repair',
    name: 'Concrete Repair & Anchoring',
    shortName: 'Concrete Repair',
    description: 'Structural (R3/R4) repair mortars, non-shrink grouts, micro-concretes, epoxy anchoring.',
    icon: 'M4 7l8-4 8 4v10l-8 4-8-4V7zM12 3v18',
    standards: ['EN 1504-3', 'EN 1504-6', 'EN 1504-4'],
  },
  'waterproofing': {
    key: 'waterproofing',
    name: 'Waterproofing',
    shortName: 'Waterproofing',
    description: 'Cementitious (CM), acrylic (AM) and polyurethane (PU) liquid-applied membranes; bituminous systems.',
    icon: 'M12 2C12 2 5 10 5 15a7 7 0 0014 0C19 10 12 2 12 2z',
    standards: ['EN 14891', 'EN 1504-2'],
  },
  'flooring-systems': {
    key: 'flooring-systems',
    name: 'Flooring Systems',
    shortName: 'Flooring',
    description: 'Self-levelling compounds (CT), screeds, epoxy/PU topcoats, industrial flooring.',
    icon: 'M3 3h18v4H3zM3 11h18v4H3zM3 19h18',
    standards: ['EN 13813', 'EN 1504-2'],
  },
  'primers-bonding': {
    key: 'primers-bonding',
    name: 'Primers & Bonding',
    shortName: 'Primers',
    description: 'Acrylic, epoxy and polyurethane primers, bonding agents and adhesion promoters.',
    icon: 'M6 3v18M10 3v18M14 3v18M18 3v18',
    standards: ['EN 1504-4', 'EMICODE EC1'],
  },
  'sealants-joints': {
    key: 'sealants-joints',
    name: 'Sealants & Joints',
    shortName: 'Sealants',
    description: 'Polyurethane, silicone, polysulphide and hybrid sealants for expansion joints.',
    icon: 'M4 12h16M8 6v12M16 6v12',
    standards: ['ISO 11600', 'EN 15651'],
  },
  'specialty-adhesives': {
    key: 'specialty-adhesives',
    name: 'Specialty Adhesives',
    shortName: 'Specialty',
    description: 'Wood/parquet, vinyl, carpet, artificial turf, rubber flooring adhesives.',
    icon: 'M4 4l16 16M20 4L4 20',
    standards: ['ISO 17178', 'EMICODE EC1'],
  },
};

export const CATEGORY_ORDER: CategoryKey[] = [
  'tile-adhesives',
  'tile-grouts',
  'concrete-repair',
  'waterproofing',
  'flooring-systems',
  'primers-bonding',
  'sealants-joints',
  'specialty-adhesives',
];

export const BRAND_ORDER: BrandKey[] = [
  'mapei',
  'weber',
  'laticrete',
  'kerakoll',
  'pidilite',
  'xchem',
  'xcalibur',
  'vetonit',
  'colmef',
];
